// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'This branch is configured for web only. Use flutter run -d chrome.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_LNr3URR7bxyCzcLUVWFs_Ou7L92O1M',
    appId: '1:720358492427:web:cf873cb91b5eebf2f73a0e',
    messagingSenderId: '720358492427',
    projectId: 'products-managment-a23a7',
    authDomain: 'products-managment-a23a7.firebaseapp.com',
    storageBucket: 'products-managment-a23a7.firebasestorage.app',
  );
}
