// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_LNr3URR7bxyCzcLUVWFs_Ou7L92O1M',
    appId: '1:720358492427:web:cf873cb91b5eebf2f73a0e',
    messagingSenderId: '720358492427',
    projectId: 'products-managment-a23a7',
    authDomain: 'products-managment-a23a7.firebaseapp.com',
    storageBucket: 'products-managment-a23a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzQJQDG4uMPR3XFK6sDpyrvmqyQeSNWg',
    appId: '1:720358492427:android:ec6885b7674b9d8ef73a0e',
    messagingSenderId: '720358492427',
    projectId: 'products-managment-a23a7',
    storageBucket: 'products-managment-a23a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqns3KEqsBvPPFv6dZh0c9DZaidDdf5SA',
    appId: '1:720358492427:ios:f781a585d4b3d4e9f73a0e',
    messagingSenderId: '720358492427',
    projectId: 'products-managment-a23a7',
    storageBucket: 'products-managment-a23a7.firebasestorage.app',
    iosBundleId: 'com.example.productsCatelogs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqns3KEqsBvPPFv6dZh0c9DZaidDdf5SA',
    appId: '1:720358492427:ios:f781a585d4b3d4e9f73a0e',
    messagingSenderId: '720358492427',
    projectId: 'products-managment-a23a7',
    storageBucket: 'products-managment-a23a7.firebasestorage.app',
    iosBundleId: 'com.example.productsCatelogs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB_LNr3URR7bxyCzcLUVWFs_Ou7L92O1M',
    appId: '1:720358492427:web:b227fe739e254d4ff73a0e',
    messagingSenderId: '720358492427',
    projectId: 'products-managment-a23a7',
    authDomain: 'products-managment-a23a7.firebaseapp.com',
    storageBucket: 'products-managment-a23a7.firebasestorage.app',
  );
}
